language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install
  - npm install ejs

before_install:
  - chmod +x node_modules
  

before_script:
  - chmod +x node_modules
  #- npm install -g gulp
  - npm install -g hexo-cli


script:
  - hexo clean
  - hexo g


after_script:
  - cd ./public
  - git init
  - git config user.name "xudajun"
  - git config user.email "xuzhijun_90@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/xudajun/sugar.github.io.git